# Generated by Django 3.1.5 on 2021-03-11 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bg_image_1', models.ImageField(blank=True, null=True, upload_to='custom/images/')),
                ('bg_image_2', models.ImageField(blank=True, null=True, upload_to='custom/images/')),
                ('bg_image_3', models.ImageField(blank=True, null=True, upload_to='custom/images/')),
                ('bg_image_4', models.ImageField(blank=True, null=True, upload_to='custom/images/')),
                ('bg_image_5', models.ImageField(blank=True, null=True, upload_to='custom/images/')),
                ('action', models.CharField(choices=[('FILTER', 'filter'), ('FILTER_MOTIVATION', 'filter_motivation'), ('GIF', 'gif'), ('SHINEFILTER', 'shinefilter'), ('ROTATE', 'rotate'), ('CARTOON', 'cartoon'), ('NEWS_PAPER', 'news_paper'), ('RED_BLUE', 'red_blue'), ('SHAKING', 'shaking'), ('TILES', 'tiles'), ('CLOTH_COLOR_FILTER', 'cloth_color_filter'), ('SMOKE_FILTER', 'smoke_filter'), ('CARTOON_TEAR', 'cartoon_tear')], max_length=150)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CustomFilters',
            },
        ),
    ]
