# Generated by Django 3.1.5 on 2021-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0002_auto_20210311_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfilters',
            name='output_file',
        ),
        migrations.AddField(
            model_name='customfilters',
            name='processed_image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
