# Generated by Django 3.1.5 on 2021-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0003_auto_20210312_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfilters',
            name='processed_image',
            field=models.URLField(blank=True),
        ),
    ]
