# Generated by Django 3.1.5 on 2021-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0005_auto_20210312_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfilters',
            name='processed_image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
