# Generated by Django 3.1.5 on 2021-03-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0006_auto_20210312_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfilters',
            name='processed_image',
            field=models.URLField(blank=True),
        ),
    ]
