# Generated by Django 3.1.5 on 2021-03-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0007_auto_20210312_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfilters',
            name='processed_image',
        ),
    ]
