# Generated by Django 3.1.5 on 2021-03-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0008_remove_customfilters_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfilters',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom/output/images/'),
        ),
    ]
