# Generated by Django 3.1.5 on 2021-03-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0009_customfilters_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfilters',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customfilters',
            name='action',
            field=models.CharField(choices=[('FILTER', 'filter'), ('FILTER_MOTIVATION', 'filter_motivation'), ('NEWS_PAPER', 'news_paper'), ('SHAKING', 'shaking'), ('TILES', 'tiles'), ('CLOTH_COLOR_FILTER', 'cloth_color_filter'), ('SMOKE_FILTER', 'smoke_filter'), ('CARTOON_TEAR', 'cartoon_tear')], max_length=150),
        ),
    ]
