# Generated by Django 3.1.5 on 2021-03-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0010_auto_20210313_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfilters',
            name='input_file',
            field=models.ImageField(blank=True, null=True, upload_to='custom/input/images/'),
        ),
    ]
