# Generated by Django 3.1.5 on 2021-03-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0011_auto_20210315_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfilters',
            name='action',
            field=models.CharField(choices=[('FILTER', 'filter (bg images required:2)'), ('FILTER_MOTIVATION', 'filter_motivation (bg images required:1)'), ('NEWS_PAPER', 'news_paper (bg images required:2)'), ('SHAKING', 'shaking (bg images required:1)'), ('TILES', 'tiles (bg images required:5)'), ('CLOTH_COLOR_FILTER', 'cloth_color_filter (bg images required:1)'), ('SMOKE_FILTER', 'smoke_filter (bg images required:2)'), ('CARTOON_TEAR', 'cartoon_tear (bg images required:1)')], max_length=150),
        ),
    ]
