# Generated by Django 3.1.5 on 2021-06-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0013_auto_20210317_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfilters',
            name='remove_background',
            field=models.BooleanField(default=False),
        ),
    ]
