# Generated by Django 3.1.5 on 2021-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0014_customfilters_remove_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfilters',
            name='bg_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='custom/images/'),
        ),
        migrations.AddField(
            model_name='customfilters',
            name='bg_image_7',
            field=models.ImageField(blank=True, null=True, upload_to='custom/images/'),
        ),
        migrations.AddField(
            model_name='customfilters',
            name='bg_image_8',
            field=models.ImageField(blank=True, null=True, upload_to='custom/images/'),
        ),
        migrations.AlterField(
            model_name='customfilters',
            name='action',
            field=models.CharField(choices=[('FILTER', 'filter (bg images required:2)'), ('FILTER_MOTIVATION', 'filter_motivation (bg images required:1)'), ('NEWS_PAPER', 'news_paper (bg images required:2)'), ('SHAKING', 'shaking (bg images required:1)'), ('TILES', 'tiles (bg images required:5)'), ('CLOTH_COLOR_FILTER', 'cloth_color_filter (bg images required:1)'), ('SMOKE_FILTER', 'smoke_filter (bg images required:2)'), ('CARTOON_TEAR', 'cartoon_tear (bg images required:2)'), ('GIF', 'gif (bg images required:0)'), ('SHINEFILTER', 'shinefilter (bg images required:2)'), ('ROTATE', 'rotate (bg images required:0)'), ('CARTOON', 'cartoon (bg images required:0)'), ('RED_BLUE', 'red_blue (bg images required:0)'), ('TRIPLE_EXPOSER', 'triple_exposer (bg images required:2)'), ('INVISIBLE_FILTER', 'invisible_filter (bg images required : 1)')], max_length=150),
        ),
    ]
