# Generated by Django 3.1.5 on 2021-01-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('action', models.CharField(choices=[('FILTER', 'filter'), ('FILTER_MOTIVATION', 'filter_motivation'), ('GIF', 'gif'), ('SHINEFILTER', 'shinefilter'), ('ROTATE', 'rotate'), ('CARTOON', 'cartoon'), ('NEWS_PAPER', 'news_paper'), ('RED_BLUE', 'red_blue'), ('SHAKING', 'shaking'), ('TILES', 'tiles'), ('CLOTH_COLOR_FILTER', 'cloth_color_filter'), ('SMOKE_FILTER', 'smoke_filter'), ('CARTOON_TEAR', 'cartoon_tear')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileHashtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ManyToManyField(blank=True, to='file_app.Hashtag')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='file_app.file')),
            ],
        ),
    ]
