# Generated by Django 3.1.5 on 2021-03-10 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_app', '0002_customfilters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfilters',
            name='file',
        ),
        migrations.AddField(
            model_name='customfilters',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
