# Generated by Django 3.1.5 on 2021-03-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0004_file_custom_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfilters',
            old_name='type',
            new_name='action',
        ),
    ]
