# Generated by Django 3.1.5 on 2021-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0005_auto_20210310_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfilters',
            name='bg_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='custom/images/'),
        ),
        migrations.AddField(
            model_name='customfilters',
            name='bg_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='custom/images/'),
        ),
    ]
