# Generated by Django 3.1.5 on 2021-03-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomFilters', '0001_initial'),
        ('file_app', '0006_auto_20210310_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='custom_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomFilters.customfilters'),
        ),
        migrations.DeleteModel(
            name='CustomFilters',
        ),
    ]
