# Generated by Django 3.1.5 on 2021-03-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0007_auto_20210311_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='file',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='file',
            name='action',
            field=models.CharField(choices=[('FILTER', 'filter'), ('FILTER_MOTIVATION', 'filter_motivation'), ('GIF', 'gif'), ('SHINEFILTER', 'shinefilter'), ('ROTATE', 'rotate'), ('CARTOON', 'cartoon'), ('NEWS_PAPER', 'news_paper'), ('RED_BLUE', 'red_blue'), ('SHAKING', 'shaking'), ('TILES', 'tiles'), ('CLOTH_COLOR_FILTER', 'cloth_color_filter'), ('SMOKE_FILTER', 'smoke_filter'), ('CARTOON_TEAR', 'cartoon_tear'), ('TRIPLE_EXPOSER', 'triple_exposer')], max_length=50),
        ),
    ]
