# Generated by Django 3.1.5 on 2021-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0008_auto_20210316_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='action',
            field=models.CharField(choices=[('FILTER', 'filter'), ('FILTER_MOTIVATION', 'filter_motivation'), ('GIF', 'gif'), ('SHINEFILTER', 'shinefilter'), ('ROTATE', 'rotate'), ('CARTOON', 'cartoon'), ('NEWS_PAPER', 'news_paper'), ('RED_BLUE', 'red_blue'), ('SHAKING', 'shaking'), ('TILES', 'tiles'), ('CLOTH_COLOR_FILTER', 'cloth_color_filter'), ('SMOKE_FILTER', 'smoke_filter'), ('CARTOON_TEAR', 'cartoon_tear'), ('TRIPLE_EXPOSER', 'triple_exposer'), ('INVISIBLE_FILTER', 'invisible_filter'), ('DUCK_GIF', 'duck_gif')], max_length=50),
        ),
    ]
